### ISSUE TITLE
Embedium imcompatibility

### ISSUE THREAD

**Issue by Tytrigger** [Tau-ri-Dev/Mod-JSG-1.20.x#10] opened 2024-02-03 20:52 UTC
All colors are gone from the world besides the stargate once it is placed and operational even got an incoming wormhole from the gate.

![2024-02-03_12 31 44](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/assets/104540003/2e48508b-e4cf-47af-b464-f2b08d9adbce)
 Currently loaded mods are
-Apple skin
-Attribute Fix
-Balm(Forge edition)
-Baubley heart Canisters
-Better Chunk loading
-Better invisiblity
-Chunk sending
-clumps
-Colorful hearts
-Connectivity
-Create
-cupboard
-Curios API
-Dynamic View
-Embedium
-Embedium extra's by Anthxny
-Embedium++
-Entity Culling Fabric/Forge
-Essential Mod
-Farsight [forge]
-Ferrite Core ((Neo)forge)
-Fix Gpu memory Leak [forge/fabric]
-From the fog By Lunar eclipse Studios (This one shouldn't even be able to do anything to other mods as it is based off a datapack)
-Journeymap
-Just Enough Items
-Just Enough professions
-Just Enough Resources
-Just Stargate Mod (1.20.1 Alpha 5.0.0.0)
-Max health fix
-ModernFix
-NetherPortalfix
-Server Performance / Smooth chunk save [Forge/fabric]
-Sophisticated Backpacks
-Sophisticated Core
-Spark
-Starlight [forge]
-TexTrue's Embedium Options
-waystones

**Comment by Tytrigger** [comment] 2024-02-03 20:52
I didn't crash so I've got no Error log or Error code sorry.

**Comment by xg787** [comment] 2024-02-03 20:53
it is caused by embedium so remove it

**Comment by Tytrigger** [comment] 2024-02-03 20:57
Is their a reason that Embedium is causing this or is it just an texture glitch from their texture optimization code?

**Comment by xg787** [comment] 2024-02-03 20:57
idk why it happens but it happens

**Comment by Tytrigger** [comment] 2024-02-03 20:59
Do you have a suggestion for other optimization mods that work with the mod without any problems? My computer is a little outdated and struggles to run the newer versions of minecraft without any significant optimizations.

**Comment by MineDragonCZ** [comment] 2024-02-03 21:00
try just remove embedium++

**Comment by Tytrigger** [comment] 2024-02-03 21:07
Removing Embedium ++ Has fixed the texture glitch and all color has returned to the world.
Is their a specific reason for this single addon breaking everything most of it's code is optimization?

**Comment by MineDragonCZ** [comment] 2024-02-04 16:13
Try open issue on Embedium project, because this is state from their CF site:

```
Compatibility
Generally Embeddium should work out of the box with many more mods than Rubidium. However, given the scope of changes it makes to the renderer, it may have compatibility issues with some mods that use advanced rendering. Please open an issue if you experience problems. Some issues may require changes to be made in the other mod but it's good to have them documented.
```

**Comment by onepieceluffyy** [comment] 2024-02-06 01:14
I can get this issue to occur with just Embeddium & JSG by toggling the programmer art resource pack. With Oculus+ModernFix+FerriteCore installed, using F3 + T also causes the issue.

**Comment by cyberdragon442** [comment] 2024-02-24 04:00
The latest version 5.0.1.0 seems to just crash with embeddium installed.

**Comment by MineDragonCZ** [comment] 2024-02-27 18:51
> The latest version 5.0.1.0 seems to just crash with embeddium installed.

Log?

**Comment by MineDragonCZ** [comment] 2024-03-23 21:43
> > > The latest version 5.0.1.0 seems to just crash with embeddium installed.
> > 
> > 
> > Log?
> 
> It loaded fine this time but crashed on entering a world (I updated Embeddium since the first crash). [latest.log](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/files/14430544/latest.log) [debug.log](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/files/14430546/debug.log) Tried a second time and it did crash on startup. [latest.log](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/files/14430640/latest.log) [debug.log](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/files/14430641/debug.log)

I don't see anything JSG related

**Comment by cyberdragon442** [comment] 2024-03-24 11:22
> > > > The latest version 5.0.1.0 seems to just crash with embeddium installed.
> > > 
> > > 
> > > Log?
> > 
> > 
> > It loaded fine this time but crashed on entering a world (I updated Embeddium since the first crash). [latest.log](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/files/14430544/latest.log) [debug.log](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/files/14430546/debug.log) Tried a second time and it did crash on startup. [latest.log](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/files/14430640/latest.log) [debug.log](https://github.com/Tau-ri-Dev/Mod-JSG-1.20.x/files/14430641/debug.log)
> 
> I don't see anything JSG related

Well it only crashes/fails to load with both JSG and Embeddium enabled. From the issue report over on Embeddium, they say JSG might be causing a VRAM overload due to loading too many large textures at once, though that is only a theory from someone experiencing a similar issue.

**Comment by MineDragonCZ** [comment] 2024-03-27 23:14
Fixed in dev

**Closed by MineDragonCZ** 2024-03-27 23:14 UTC
