### ISSUE TITLE
Horizontal Gate completely kills the world

### ISSUE THREAD

**Issue by ThatSteveThing** [Tau-ri-Dev/Mod-JSG-1.20.x#15] opened 2024-02-04 20:38 UTC
When trying to make a horizontal gate, placing the final gate block causes the game to completely freeze, then the world crashes and boots you back to the launcher.

Upon reloading into the world, the game freezes again and crashes again, effectively killing the world stone dead.

**Comment by MineDragonCZ** [comment] 2024-02-05 12:24
Can you provide a log, please??

**Comment by MineDragonCZ** [comment] 2024-02-05 12:49
Possible duplicate of #8

**Closed by MineDragonCZ** 2024-02-05 12:49 UTC
